### ISSUE TITLE
Error using Kobo module

### ISSUE THREAD

**Issue by ashfaqfarooqui** [karlicoss/orger#2]
Thanks for this package, it is something I've been wishing for a long time. 

Firstly, I've not been very involved with using Python, so it was not straight forward to me how to use the different packages you have (as requirements) to run Orger. Specifically getting ``my_configuration`` in the correct paths. I hope you can make this a self-contained package which does not require additional packages to be explicitly installed. [Maybe, I'm totally wrong and have somehow misread your instructions, and doing something wrong; I'm not sure].

When I got everything to work together, I get the following error while importing kobo annotations
```shell
Traceback (most recent call last):
  File "/home/ashfaqf/Code/orger/modules/kobo.py", line 35, in <module>
    KoboView.main()
  File "/home/ashfaqf/.local/lib/python3.7/site-packages/orger/org_view.py", line 64, in main
    inst._run(to=args.to)
  File "/home/ashfaqf/.local/lib/python3.7/site-packages/orger/org_view.py", line 72, in _run
    org_tree = self.make_tree()
  File "/home/ashfaqf/.local/lib/python3.7/site-packages/orger/org_view.py", line 86, in make_tree
    for p in self.get_items():
  File "/home/ashfaqf/Code/orger/modules/kobo.py", line 20, in get_items
    for page in get_books_with_highlights():
  File "/home/ashfaqf/Code/orger/my/my_configuration/repos/kobuddy/src/kobuddy/__init__.py", line 724, in get_books_with_highlights
    highlights = get_highlights(**kwargs)
  File "/home/ashfaqf/Code/orger/my/my_configuration/repos/kobuddy/src/kobuddy/__init__.py", line 675, in get_highlights
    return list(sorted(_iter_highlights(**kwargs), key=lambda h: h.created))
  File "/home/ashfaqf/Code/orger/my/my_configuration/repos/kobuddy/src/kobuddy/__init__.py", line 657, in _iter_highlights
    if h not in yielded:
  File "/home/ashfaqf/Code/orger/my/my_configuration/repos/kobuddy/src/kobuddy/__init__.py", line 212, in __hash__
    return hash(self._key)
  File "/home/ashfaqf/Code/orger/my/my_configuration/repos/kobuddy/src/kobuddy/__init__.py", line 206, in _key
    return (self.dt, self.text, self.annotation)
  File "/home/ashfaqf/Code/orger/my/my_configuration/repos/kobuddy/src/kobuddy/__init__.py", line 154, in dt
    return unwrap(_parse_utcdt(self.row['DateCreated']))
  File "/home/ashfaqf/Code/orger/my/my_configuration/repos/kobuddy/src/kobuddy/common.py", line 12, in unwrap
    assert x is not None
AssertionError

```

What am I doing wrong here?

**Comment by karlicoss** [comment]
Hi @ashfaqfarooqui . Glad you tried it!
I think you've done the setup right actually!

The exception has something to do with database structure, in particular `DateCreated` row is none for some reason, which I've never seen on my Kobo. Could you please insert a debug `print` [here, in `dt` function](https://github.com/karlicoss/kobuddy/blob/master/src/kobuddy/__init__.py#L154), like this:

```  
        print(self.row)
        return unwrap(_parse_utcdt(self.row['DateCreated']))
```
, and post the result please? That'll help me understand how to fix it properly.

In the meantime, I think I'll make processing more defensive and if datetime is missing in the database just display the highlight without it. I'll let you know when I'm done. I think you can also get around it for now if you modify the same function I mentioned above to something like:

```
    @property
    def dt(self) -> datetime:
        res = _parse_utcdt(self.row['DateCreated'])
        if res is None:
            return datetime.now(tz=pytz.utc) # temporary fallback to current time
        else:
            return res
```


P.S. Sorry for complicated setup with all the python packages etc. I've spent a while thinking about it and it's simplest what I got so far (considering you need side packages, private configuration etc). Can you please share what would be your ideal way of configuring/setting up? Vague thoughts are fine too even if you don't have something specific in mind. That would help me a lot in understanding how to simplify it further :)
