### ISSUE TITLE
Error upon installation

### ISSUE THREAD

**Issue by AtomicNess123** [karlicoss/orger#21]
Hi! I'm finally getting to install this whole thing :) 
After installing the package, I run

`python3 -m orger.modules.instapaper --help   `

But get an error:

```
/Users/gahis/.local/lib/python3.7/site-packages/my/core/init.py:45: UserWarning: my.config package isn't found! (expected at /Users/gahis/.config/my). This is likely to result in issues.
  warnings.warn(f"my.config package isn't found! (expected at {mycfg_dir}). This is likely to result in issues.")
Traceback (most recent call last):
  File "/Users/gahis/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/gahis/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/gahis/.local/lib/python3.7/site-packages/orger/modules/instapaper.py", line 6, in <module>
    from my.instapaper import pages
  File "/Users/gahis/.local/lib/python3.7/site-packages/my/instapaper.py", line 7, in <module>
    from my.config import instapaper as config
ImportError: cannot import name 'instapaper' from 'my.config' (/Users/gahis/.local/lib/python3.7/site-packages/my/config/__init__.py)
```

Any help welcome, thanks.

**Comment by karlicoss** [comment]
Hi! 
Well, it's warned you ;)  `my.config package isn't found! (expected at /Users/gahis/.config/my). This is likely to result in issues.`

Can you try double checking HPI setup guide, in particular, [troubleshooting section](https://github.com/karlicoss/HPI/blob/master/doc/SETUP.org#troubleshooting)? Also what's your HPI version? You can check it with `python3 -m pip show hpi`

**Comment by AtomicNess123** [comment]
Thanks. I don't know any programming, but would love to make this work! Apologies for my question if they are basic.

I ran the doctor and got this, which tells that the config file is at /Users/gahis/Library/Application Support/my/my/config/__init__.py. However, this python file is completely empty.

```
✅ import order: ['/Users/gahis/HPI/my']
✅ config file: /Users/gahis/Library/Application Support/my/my/config/__init__.py
❗ mypy not found, so can't check config with it. See https://github.com/python/mypy#readme if you want to install it and retry
  /Users/gahis/HPI/my/common.py:2: UserWarning: DEPRECATED! Please use my.core.common instead.
    high("DEPRECATED! Please use my.core.common instead.")
  /Users/gahis/HPI/my/error.py:2: UserWarning: DEPRECATED! Please use my.core.error instead.
    high("DEPRECATED! Please use my.core.error instead.")
  /Users/gahis/HPI/my/books/kobo.py:3: UserWarning: my.books.kobo is deprecated! Please use my.kobo instead!
    warnings.high('my.books.kobo is deprecated! Please use my.kobo instead!')
  /Users/gahis/HPI/my/books/kobo.py:3: UserWarning: my.books.kobo is deprecated! Please use my.kobo instead!
    warnings.high('my.books.kobo is deprecated! Please use my.kobo instead!')
✅ OK  : my.calendar.holidays                              
❗      - stats:                      computing failed
   Traceback (most recent call last):
     File "/Users/gahis/HPI/my/core/__main__.py", line 220, in modules_check
       res = stats()
     File "/Users/gahis/HPI/my/calendar/holidays.py", line 57, in stats
       h = is_holiday(d)
     File "/Users/gahis/HPI/my/calendar/holidays.py", line 42, in is_holiday
       return not _calendar().is_working_day(day)
     File "/Users/gahis/HPI/my/calendar/holidays.py", line 17, in _calendar
       from workalendar.registry import registry # type: ignore
   ModuleNotFoundError: No module named 'workalendar'
  /Users/gahis/HPI/my/coding/github.py:3: UserWarning: my.coding.github is deprecated! Please use my.github.all instead!
    warnings.warn('my.coding.github is deprecated! Please use my.github.all instead!')
  /Users/gahis/HPI/my/coding/github.py:3: UserWarning: my.coding.github is deprecated! Please use my.github.all instead!
    warnings.warn('my.coding.github is deprecated! Please use my.github.all instead!')
❗ Skipped 73 modules: ['my.bluemaestro', 'my.cfg', 'my.coding', 'my.common', 'my.demo', 'my.emfit', 'my.endomondo', 'my.error', 'my.fbmessenger', 'my.foursquare', 'my.hypothesis', 'my.instapaper', 'my.jawbone', 'my.kobo', 'my.lastfm', 'my.materialistic', 'my.media', 'my.orgmode', 'my.pdfs', 'my.photos', 'my.pinboard', 'my.pocket', 'my.reddit', 'my.rescuetime', 'my.roamresearch', 'my.rtm', 'my.smscalls', 'my.stackexchange', 'my.taplog', 'my.bluemaestro.check', 'my.body.blood', 'my.body.weight', 'my.body.exercise.cardio', 'my.body.exercise.cross_trainer', 'my.body.sleep.common', 'my.body.sleep.main', 'my.books.kobo', 'my.coding.codeforces', 'my.coding.commits', 'my.coding.github', 'my.coding.topcoder', 'my.emfit.plot', 'my.github.all', 'my.github.common', 'my.github.gdpr', 'my.github.ghexport', 'my.google.takeout.html', 'my.google.takeout.paths', 'my.jawbone.plots', 'my.kython.kompress', 'my.lastfm.fill_influxdb', 'my.location.google', 'my.location.home', 'my.media.imdb', 'my.media.movies', 'my.media.youtube', 'my.photos.utils', 'my.reading.goodreads', 'my.reading.polar', 'my.rss.all', 'my.rss.common', 'my.rss.feedbin', 'my.rss.feedly', 'my.time.tz.common', 'my.time.tz.main', 'my.time.tz.via_location', 'my.twitter.all', 'my.twitter.archive', 'my.twitter.common', 'my.twitter.twint', 'my.vk.all', 'my.vk.favorites', 'my.vk.vk_messages_backup']. Pass --all if you want to see them.

```

**Comment by AtomicNess123** [comment]
BTW, I am interested mainly in the hypothesis module.
BTW Version: 0.2.20201004.dev40

**Comment by karlicoss** [comment]
> Thanks. I don't know any programming, but would love to make this work! Apologies for my question if they are basic.

No worries at all! Happy to help.

Great, the version looks good. The output also looks as expected: some warnings, but they are expected (although I should probably make them look less scary).

Let's carry on discussion in https://github.com/karlicoss/HPI/issues/110 ? Just so we do it in one place :)
